-- Core tables, constraints and indexes.

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 40),
  role public.user_role not null default 'participant',
  created_at timestamptz not null default now()
);

create table public.clubs (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  short_name text not null,
  league text not null,
  country text not null,
  league_rank smallint not null check (league_rank between 1 and 5),
  external_source_id text not null unique,
  primary_color text check (primary_color ~ '^#[0-9A-Fa-f]{6}$'),
  secondary_color text check (secondary_color ~ '^#[0-9A-Fa-f]{6}$'),
  crest_path text,
  constraint clubs_league_rank_unique unique (league, league_rank)
);

-- A player belongs to one club at scrape time, so a plain FK is enough (no N:M table).
create table public.players (
  id uuid primary key default gen_random_uuid(),
  external_source_id text not null unique,
  club_id uuid not null references public.clubs (id) on delete cascade,
  name text not null,
  position text not null,
  overall_rating smallint check (overall_rating between 1 and 99),
  age smallint check (age between 14 and 60),
  nationality text,
  shirt_number smallint check (shirt_number between 0 and 99),
  photo_path text
);

create table public.tournaments (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(btrim(name)) > 0),
  status public.tournament_status not null default 'DRAFT',
  current_round integer not null default 0 check (current_round >= 0),
  max_participants integer not null default 25 check (max_participants between 2 and 25),
  started_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.tournament_participants (
  id uuid primary key default gen_random_uuid(),
  tournament_id uuid not null references public.tournaments (id) on delete cascade,
  user_id uuid not null references public.profiles (id),
  club_id uuid not null references public.clubs (id),
  joined_at timestamptz not null default now(),
  -- One entry per user per tournament.
  constraint tournament_participants_user_unique unique (tournament_id, user_id),
  -- No two participants can share a club in the same tournament.
  constraint tournament_participants_club_unique unique (tournament_id, club_id),
  -- Target of the composite FKs from matches (forces same-tournament participants).
  constraint tournament_participants_id_tournament_unique unique (id, tournament_id)
);

create table public.matches (
  id uuid primary key default gen_random_uuid(),
  tournament_id uuid not null references public.tournaments (id) on delete cascade,
  round integer not null check (round >= 1),
  leg smallint not null check (leg in (1, 2)),
  home_participant_id uuid not null,
  away_participant_id uuid not null,
  status public.match_status not null default 'SCHEDULED',
  home_score smallint check (home_score >= 0),
  away_score smallint check (away_score >= 0),
  finished_at timestamptz,
  confirmed_at timestamptz,
  resolved_by uuid references public.profiles (id),
  resolution_note text,
  created_at timestamptz not null default now(),
  constraint matches_home_fk foreign key (home_participant_id, tournament_id)
    references public.tournament_participants (id, tournament_id),
  constraint matches_away_fk foreign key (away_participant_id, tournament_id)
    references public.tournament_participants (id, tournament_id),
  constraint matches_home_away_differ check (home_participant_id <> away_participant_id),
  -- Each ordered pair (home, away) appears once: first leg A-B, second leg B-A.
  constraint matches_fixture_unique unique (tournament_id, home_participant_id, away_participant_id),
  -- Score exists exactly from the moment the home player finishes the match.
  constraint matches_score_consistency check (
    ((status in ('SCHEDULED', 'ACTIVE')) = (home_score is null))
    and ((home_score is null) = (away_score is null))
  ),
  constraint matches_resolved_requires_admin check (status <> 'RESOLVED' or resolved_by is not null)
);

-- id is generated by the client (offline queue) so re-sending is idempotent.
create table public.match_events (
  id uuid primary key,
  match_id uuid not null references public.matches (id) on delete cascade,
  participant_id uuid not null references public.tournament_participants (id),
  player_id uuid not null references public.players (id),
  type public.event_type not null,
  minute smallint not null check (minute between 1 and 120),
  created_by uuid not null references public.profiles (id),
  created_at timestamptz not null default now()
);

create table public.lineups (
  participant_id uuid primary key references public.tournament_participants (id) on delete cascade,
  formation text not null check (char_length(formation) between 1 and 20),
  positions jsonb not null default '[]'::jsonb check (jsonb_typeof(positions) = 'array'),
  updated_at timestamptz not null default now()
);

create index matches_tournament_round_idx on public.matches (tournament_id, round);
create index matches_status_idx on public.matches (status);
create index match_events_match_idx on public.match_events (match_id);
create index players_club_idx on public.players (club_id);
-- Used by every RLS policy that asks "does this participant belong to auth.uid()?".
create index tournament_participants_user_idx on public.tournament_participants (user_id);
